Incorporate Wikidata into authorities for subject transform.
utkdigitalinitiatives/utk-fedora-fedoragsearch-solr-config pull request #48
Opened 2020-08-05 21:07 UTC by mlhale7

**Jira Issue**: [DIGITAL-789](https://jirautk.atlassian.net/browse/TICKET-NUMBER)

## What does this Pull Request do?

Our existing transform does not include Wikidata as a possible authority. This PR adds this authority. Here's a new record that includes a Wikidata entity - https://digital.lib.utk.edu/collections/islandora/object/mencross%3A142/datastream/MODS/view

## How should this be tested?

A description of what steps someone could take to:

1. Add an object to islandora vagrant
2. Look at its Solr document:  [http://localhost:8080/solr/collection1/select?q=PID%3A%22test:1%22&fl=*&wt=json&indent=true](http://localhost:8080/solr/collection1/select?q=PID%3A%22test:1%22&fl=*&wt=json&indent=true)
3. If overwriting a transform, replace your transform at this path: /var/lib/tomcat7/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/index/FgsIndex/islandora_transforms/
4. Restart tomcat or solr: http://localhost:8080/manager/
5. Update gsearch for your object with curl or python or GUI:

```python

import requests

my_pid = 'test:1'
requests.post(f'http://localhost:8080/fedorafedoragsearch/rest?operation=updateIndex&action=fromPid&value={my_pid}', auth=('fedoraAdmin', 'fedoraAdmin'))

```

## Interested parties

@CanOfBees @markpbaggett

2020-08-08 02:11 UTC, CanOfBees commented
@mlhale7 reviewing this now.

2020-08-08 03:27 UTC, CanOfBees requested changes
@mlhale7 I think we're going to need to add a rule to catch `subject/name/namePart` - we don't have one currently - and unless this is another incoming PR. Would you like to incorporate that here? For testing this PR, I added the following rule at line 235:
```xml
          <xsl:when test="self::node()[mods:name]">
            <field name="utk_mods_subject_name_ms">
              <xsl:value-of select="concat(normalize-space(child::mods:name/mods:namePart), $vAuthority)"/>
            </field>
          </xsl:when>
```

with that addition to your change, I have this in my index:
```
        "utk_mods_subject_name_ms": [
          "George Watts, (Wikidata)",
          "University of Tennessee, Knoxville, (Library of Congress Name Authority File)",
          "Tennessee Volunteers cross country, (Wikidata)"
        ]
```

2020-08-10 13:40 UTC, mlhale7 commented
@CanOfBees - thanks for noticing this. Yes, you are correct in that we need to have a rule to catch the namePart values. The additions to the index look good.

2020-08-10 14:19 UTC, CanOfBees approved these changes
@mlhale7 I think this fixes the `subject/name` problem - thanks for incorporating it.

2020-08-10 15:11 UTC, merged